blog/urls.py
from blog import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("list", views.PostList.as_view(), name="post-list"),
    path(
        "post/<int:pk>",
        views.PostDetail.as_view(),
        name="post-detail",
    ),
    path(
        "post/create",
        views.PostCreateView.as_view(),
        name="post-create",
    ),
]

monprojet/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "blog/",
        include("blog.urls", "blog"),
    ),
]

blog/models.py
from django.db import models


class Post(models.Model):
    """Model for Post"""

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500, blank=True, null=True)
    author = models.ForeignKey(
        "Author",
        related_name="posts",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title


class Author(models.Model):
    """Model for Author"""

    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "description")

blog/views.py
from blog.forms import PostForm
from blog.models import Post
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView


def home_view(request):
    return HttpResponse("<h1>Bienvenue !</h1>")


class PostList(ListView):
    """Post list view"""

    model = Post


class PostDetail(DetailView):
    """Post detail view"""

    model = Post


class PostCreateView(CreateView):
    """Post create view"""

    form_class = PostForm
    template_name = "blog/post_form.html"

    def get_success_url(self, **kwargs):
        return reverse(
            "blog:post-detail",
            kwargs={"pk": self.object.pk},
        )

blog/templates/blog/post_detail.html
<div style="margin: 50px 100px">
	<h1>{{ post.title }}</h1>

	{% if post.author %}
	<p>Article rédigé par {{ post.author.name }}</p>
	{% endif %}

	<dl>
		<dt>Description</dt>
		<dd>{{ post.description }}</dd>
	</dl>

	<a href="{% url 'blog:post-list' %}"> Revenir à la liste </a>
</div>

blog/templates/blog/post_form.html
<div style="margin: 50px 100px">
	<a href="{% url 'blog:post-list' %}"> Revenir à la liste </a>
	<form method="post">
		{% csrf_token %} {{ form.as_p }}
		<input type="submit" value="Valider" />
	</form>
</div>

blog/templates/blog/post_list.html
<dl style="margin: 50px 100px">
	{% if object_list %} {% for post in object_list %}
	<li>
		<a href="{% url 'blog:post-detail' post.pk %}"> {{ post.title }} </a>
	</li>
	{% endfor %} {% else %}
	<p>Aucun article!</p>
	{% endif %}
	<div>
		<a href="{% url 'blog:post-create' %}"> Proposer un article </a>
	</div>
</dl>